### ISSUE TITLE
Using xacro in ROS 2

### ISSUE THREAD

**Issue by max-assel** [ros/xacro#243]
I downloaded ROS 2 dashing for windows 10 through this link: https://index.ros.org/doc/ros2/Installation/Dashing/Windows-Install-Binary/ and then followed this tutorial to set up the xacro package since it was not included in the ROS 2 installation: https://index.ros.org/doc/ros2/Tutorials/Workspace/Creating-A-Workspace/

However, now when I try to run "ros2 run xacro xacro --xacro-ns custom.xacro > custom.urdf" in the dev_ws that I cloned the xacro package to, I get the following:

Traceback (most recent call last):

File "C:\dev\ros2-dashing\Scripts\ros2-script.py", line 11, in <module> load_entry_point('ros2cli==0.7.10', 'console_scripts', 'ros2')()

File "C:\dev\ros2-dashing\Lib\site-packages\ros2cli\cli.py", line 69, in main rc = extension.main(parser=parser, args=args)

File "C:\dev\ros2-dashing\Lib\site-packages\ros2run\command\run.py", line 72, in main return run_executable(path=path, argv=args.argv, prefix=prefix)

File "C:\dev\ros2-dashing\Lib\site-packages\ros2run\api__init__.py", line 61, in run_executable process = subprocess.Popen(cmd)

File "c:\python37\lib\subprocess.py", line 800, in __init__ restore_signals, start_new_session)

File "c:\python37\lib\subprocess.py", line 1207, in _execute_child startupinfo)

OSError: [WinError 193] %1 is not a valid Win32 application

Would anyone be able to help me with this?

**Comment by rhaschke** [comment]
This doesn't seem to be a xacro problem. Looks like the binary/script to execute is not found by Windows. Please check your workspace settings and direct this questions to ROS answers.
The github issues are intended for bug reports.
